### PR TITLE
Text updates

### PR DESCRIPTION
**Pull request by xibe**
Hello!

I love the project, and thought I could help with a bit of proofreading, mostly of the documentation.

I hope it's useful :)

Cheers!

### CODE REVIEW

**Comment by steffest** [comment]
Thanks! Much appreciated. 
Writing proper English is much harder then writing proper code, right?

**Comment by xibe** [comment]
My pleasure! It's only a tiny contribution compared to your huge work on this :)

One thing I'd like to have your opinion about: I "standardized" the app name as Bassoontracker, but what's your official take on it? I've seen several variations:
* Bassoontracker
* BassoonTracker
* Bassoon Tracker
Which one is it? :)

**Comment by steffest** [comment]
Good question ... 
When I first started playing around with generating sounds with WebAudio, One of the first things I made was some kind of "wind-generator" that you could just leave running to play an endlessly changing wind-like sound. When I start adding some other filters it sounded more like an instrument, something like a bassoon. 
So I called it "Bassoon"
When I went further I just kept the bassoon name thinking that maybe someday I could build it into a fully fledged "studio" where the tracker was 1 component of.
Anyway ... I think I'll opt for BassoonTracker

**Comment by xibe** [comment]
I love this origin story of the name, it should be in the FAQ :)

Here you go, then: #49.

Cheers!

**Pull request merged**
